include: package:very_good_analysis/analysis_options.yaml
analyzer:
  language:
    strict-casts: true
    strict-raw-types: false

  errors:
    close_sinks: ignore
    document_ignores: ignore
    lines_longer_than_80_chars: ignore
    missing_required_param: error
    missing_return: error

  exclude:
    - test/.test_coverage.dart
    - lib/generated_plugin_registrant.dart
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.config.dart"
    - "**/firebase_options.dart"
    - "**/flavors.dart"
    - "**/*.chopper.dart"
    # - "**/main_dev.dart"
    # - "**/main_prod.dart"

linter:
  rules:
    public_member_api_docs: false
    constant_identifier_names: false
    always_put_required_named_parameters_first: false
    avoid_positional_boolean_parameters: false
    directives_ordering: false
    sort_pub_dependencies: false
    use_if_null_to_convert_nulls_to_bools: false
    avoid_field_initializers_in_const_classes: false
    document_ignores: false
  