name: bradderly
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

isar_version: &isar_version 3.1.0+1

dependencies:
  flutter:
    sdk: flutter

  provider: 6.1.2
  cupertino_icons: ^1.0.8
  get_it: 7.7.0
  flutter_bloc: 8.1.6
  hydrated_bloc: 9.1.5
  bloc_concurrency: 0.2.5
  dartz: 0.10.1
  equatable: 2.0.7
  collection: 1.19.0
  flutter_dotenv: 5.2.1
  flutter_native_splash: 2.4.4
  logger: 1.4.0
  intl: 0.19.0
  nil: 1.1.1
  json_annotation: 4.9.0
  chopper: 7.4.0
  injectable: 2.5.0
  path_provider: 2.1.5
  isar: *isar_version
  isar_flutter_libs: *isar_version
  flutter_svg: 2.0.17
  gap: 3.0.1
  go_router: 14.6.3
  record: 5.2.0
  path: 1.9.0
  http: 1.2.2
  rxdart: 0.28.0
  csv2json: 0.0.3 
  device_info_plus: 11.2.2
  package_info_plus: 8.1.4
  crypto: 3.0.6
  connectivity_plus: 6.1.2
  synchronized: 3.3.0+3
  dropdown_button2: 2.3.9
  keyboard_actions: 4.2.0
  flutter_localization: 0.3.1
  flutter_keyboard_visibility: 6.0.0
  scrolls_to_top: 2.1.1
  csv: 6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer: 5.13.0
  build_runner: 2.4.13
  build_verify: 3.1.0
  flutter_flavorizr: 2.2.3
  flutter_gen_runner: 5.8.0
  flutter_lints: 5.0.0
  very_good_analysis: 7.0.0
  injectable_generator: 2.4.2
  chopper_generator: 7.4.0
  json_serializable: 6.8.0
  swagger_dart_code_generator: 2.11.11
  import_sorter: 4.6.0
  isar_generator: *isar_version
  go_router_builder: 2.7.1

flutter_gen:
  output: lib/presentation/generated/assets/
  line_length: 160
  integrations:
    flutter_svg: true
  exclude:
    - assets/fonts/

flutter_native_splash:
  color: "#594eb2"
  android_12:
    color: "#594eb2"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/env/
    - assets/img/
    - assets/i18n/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700

        